### ISSUE TITLE
The website download link

### ISSUE THREAD

**Issue by arupgsh** [TheSkin/Skin-WordPress-Theme#22]
The download link on Skin website is not working.

**Comment by ahmedkaludi** [comment]
Hi @arupgsh - First of all, I am so glad that you are helping us with this!! 

Are you sure its not working?, Because alot of people have been downloading it and using it.. 
Which browser are you using?

**Comment by arupgsh** [comment]
I'm using google chrome 64 bit v 48.0.2540.0 and 23Mbps connection. The download link "http://theskin.io/download/119/" keeps loading for 5 mins returning nothing.

**Comment by ahmedkaludi** [comment]
That's strange, because it is working for me and many others. I think I should create a /download page where we can add this link and an alternative direct zip link as well...

What do you say? 

Meanwhile, you can download it from https://github.com/TheSkin/Skin-WordPress-Theme/archive/master.zip

- Ahmed

**Comment by arupgsh** [comment]
Yeah that will be helpful. By the way I've already downloaded it from Github.

**Comment by ahmedkaludi** [comment]
Thank you Arup! Don't forget to help us with a Star on the Git repo.

Any help with getting the word out to the community will be highly appreciated!

**Comment by arupgsh** [comment]
I'll share a review of this framework in my blog http://www.wptron.com
